Algoritmo "semnome"
// Data atual  : 30/11/2022
Var
   // Seção de Declarações das variáveis
   c, n, f: inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   f <- 1
   escreval("Você quer o fatorial de que número?")
   leia (n)
   para c de n ate 1 passo -1 faca
        F <- F*C
   fimpara
   escreval("O valor do fatorial de ", n, " é igual a ", f)





Fimalgoritmo