Algoritmo "semnome"
//
Var
// Seção de Declarações das variáveis 
lado, area, perimetro: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Informe o lado do quadrado")
leia (lado)
escreval ("O lado do quadrado é:", lado)

perimetro <- (4*lado)
escreval ("Então o perímetro do quadrado será: ", perimetro)

area <- (lado^2)
escreval ("E a área do quadrado é: ", area)


Fimalgoritmo