Algoritmo "semnome"
// Escreva um algoritmo que mostre os 1000 primeiros números pares,
// a partir de 2.

Var
// Seção de Declarações das variáveis 
   pares: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   pares <- 0
   enquanto pares < 1001 faca
   escreval (pares)
   pares <- pares + 2
   fimenquanto
   escreval ("Acabou os números pares de 0 a 1000 (mil)")


Fimalgoritmo