Algoritmo "semnome"
//
// Data atual  : 29/11/2022
Var
   // Seção de Declarações das variáveis

   codigo: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   escreval ("Digite o código:")
   leia (codigo)
   enquanto (codigo <> 123456) faca
      escreval ("Acesso negado")
      escreval ("Tente novamente")
      leia (codigo)
   fimenquanto
   escreval("Acesso Liberado")







Fimalgoritmo