Algoritmo "Soma de 2 numeros inteiros"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/11/2022
Var
// Seção de Declarações das variáveis 
n1, n2, problema: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Informe um número")
leia (n1)
escreval ("Informe outro número")
leia (n2)

Escreval ("A soma de desses números é ", n1+n2 )



Fimalgoritmo